export const FETCH_DB = 'FETCH_DB';
export const LIST_SORT_BY_LATEST ='LIST_SORT_BY_LATEST';
export const LIST_SORT_BY_POPULAR ='LIST_SORT_BY_POPULAR';
export const LIST_LOCATION_SEARCH = 'LIST_LOCATION_SEARCH'